target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
       if config.base_configuration_reference
         config.build_settings['PODS_BUILD_DIR'] = "$(SRCROOT)/../../build/ios"
         config.build_settings['SYMROOT'] = "$(SRCROOT)/../../build/ios"
         config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "16.0"
       end
       xcconfig_path = config.base_configuration_reference.real_path
       xcconfig = File.read(xcconfig_path)
       xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
       File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end